"active_program" is missing in persistent folder
Fixes:
Traceback (most recent call last):
  File "/workdir/webserver/webserver.py", line 2423, in <module>
    file = open("active_program", "r")
FileNotFoundError: [Errno 2] No such file or directory: 'active_program'