Revert alpine linux PR as that broke the installation on other Linuxes
When installing on Ubuntu (and possibly others) sudo support was broken after Alpine changes:
$ sudo ./start_openplc.sh 
Traceback (most recent call last):
  File "/home/factslinux/OpenPLC_v3/webserver/webserver.py", line 6, in <module>
    import serial.tools.list_ports
ModuleNotFoundError: No module named 'serial'